apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flaskapp
        image: gkovacs/flask_test
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 80