apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
  name: flaskapp
spec:
  ports:
  - name: http
    port: 8000
    targetPort: http
  selector:
    app: flask
  type: LoadBalancer
