apiVersion: v1
kind: PersistentVolume
metadata:
  name: gkovacs-pv1
spec:
  storageClassName: local-storage
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gkovacs-pv2
spec:
  storageClassName: local-storage
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data2"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gkovacs-pv3
spec:
  storageClassName: local-storage
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data3"