apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis-master
  selector:
    statefulset.kubernetes.io/pod-name: redis-0
