apiVersion: v1
kind: PersistentVolume
metadata:
  name: gkovacs-pv1
spec:
  storageClassName: gkovacs-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gkovacs-pv2
spec:
  storageClassName: gkovacs-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data2"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gkovacs-pv3
spec:
  storageClassName: gkovacs-local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data3"